### ISSUE TITLE
Compatability issue with Extended Days

### ISSUE THREAD

**Issue by SimulatorSia** [TheIllusiveC4/Comforts#10]
https://minecraft.curseforge.com/projects/extended-days
When you sleep in a hammock while extended days is installed, the time gets set to the morning instead of twilight/evening.

**Comment by TheIllusiveC4** [comment]
It'll take some time for me to parse through what Extended Days is doing in its code that could be causing this issue, but I'll try to figure this out as soon as I can. Thanks for letting me know.

**Comment by TheIllusiveC4** [comment]
Nevermind, easier than I thought. Anyways, I think the problem is on Extended Days' end. Basically, Extended Days is setting the time themselves since they disable the daylight cycle. The compatibility occurs because that mod assumes that you always advance to daytime, when that is not the case with Comforts installed and you sometimes want to advance to nighttime instead via the hammocks.

**Comment by SimulatorSia** [comment]
Extended Days fixed the issue. You can add Extended Days to your compatibility list if you wish.

**Comment by TheIllusiveC4** [comment]
Oh okay, thanks for letting me know!

**Comment by Sereath** [comment]
Hmm
I wasn't sure if you were still willing to take a look at the 1.12 version so I mentioned this same problem to CreativeMD instead, my bad if I assumed wrong. 
Same issue with OpticManager (which can also change the lenght of the day) of hammocks moving the time to the morning instead of the evening.

**Comment by Sereath** [comment]
Nevermind, hammocks skip to the next morning as well even without OpticManager. Just wanted to point that out.
