### ISSUE TITLE
[Feature]: Accelerate time based on percentage of sleeping player instead of skipping night/day.

### ISSUE THREAD

**Issue by HySand** [TheIllusiveC4/Comforts#108]
### What is the new feature or improvement?

Add an option that accelerates time based on percentage of sleeping player instead of skipping night/day. I tried some mods with similar feature, they eiter not support accelerate day time or not support sleeping bags or hammocks.

**Comment by TheIllusiveC4** [comment]
Unfortunately, this is outside the scope of the mod as I'm not looking to introduce changes to the sleeping mechanic. It would be fairly easy for any mod that does do this to check for sleeping bags and hammocks also, and it would be much easier for them to do that instead of me adding this kind of time acceleration.
