### ISSUE TITLE
[Bug]: Possible side effect - abundance of rain, when combo'd with Time & QW

### ISSUE THREAD

**Issue by purejosh** [TheIllusiveC4/Comforts#112]
### Minecraft Version

1.19.2

### What happened?

Do you think it's possible that your sleeping bags could be having an impact with Time & Wind? That mod allows for fast forwarding of the night cycle, instead of instantly skipping, and it also allows for longer days and nights. I'm very certain it's caused by Time & Wind, but in the off chance it could be the sleeping bags, I figured I'd ask you about your thoughts. 

### How do you trigger this bug?

Described above. 

### Loader

Fabric

### Loader Version

Fabric 1.14.11

### API Version

0.70.0

### Mod Version

6.0.3

**Comment by purejosh** [comment]
https://github.com/CmdrJane/time-and-wind/issues/18
I opened this issue on Time & Wind.

**Comment by TheIllusiveC4** [comment]
It's certainly possible, but that's just because I think almost anything is possible. Unlikely though, this is the first I've heard of this kind of issue and I don't do anything with the weather in my code. It could be a combination somehow of Comforts and Time & Wind, but I'd need to see what the Time & Wind developer has to say about the subject first
