### ISSUE TITLE
[Feature]: Too much string

### ISSUE THREAD

**Issue by McPickleSandwich** [TheIllusiveC4/Comforts#127]
### What is the new feature or improvement?

I feel like 15 string is too much for just one hammock plus the 2 rope and nails required. Especially since I first used this mod in a multiplayer world and had to collect 30 string just for a couple hammocks. I think maybe the nails should only need 2 strings to make, or they could keep the same recipe but it would produce 2 rope and nails instead of one. It would make sense realistically considering that one real life iron ingot would probably get you a whole bunch of nails. Also, I think the hammock should only cost 2-4 string instead of 6.

**Comment by TheIllusiveC4** [comment]
> I think maybe the nails should only need 2 strings to make, or they could keep the same recipe but it would produce 2 rope and nails instead of one

I'm not sure if the recipe was changed in your environment, or maybe a bug, but by default the recipe does give you 2 rope and nail. Unless you mean 2 pairs of them to hang 2 hammocks.

Ultimately, I'd rather keep the recipe as-is because it mimics the lead recipe (which is 4 string and 1 slimeball to make 2 lead, a comparable output to the 2 rope and nail).

> Also, I think the hammock should only cost 2-4 string instead of 6.

I can bring the recipe cost down to 4 string, I don't have much of an issue with that. But I can only introduce it in 1.21 at the earliest to avoid changing recipes in the middle of a major version.
