### ISSUE TITLE
[Feature]: Configure use range

### ISSUE THREAD

**Issue by andersmmg** [TheIllusiveC4/Comforts#140]
### What is the new feature or improvement?

I would like to use hammocks in my ship from Eureka and VS2, but it always says I am too far because it probably thinks it's in the "shipyard" which is how the mod works. I'd like a config option to configure or even disable the range so you can use them from far away to fix this.

**Comment by TheIllusiveC4** [comment]
Since the use range is controlled by the vanilla system as a whole, rather than per-block, this would be hard to accomplish without touching code that could potentially cause unintended side effects so I'll unfortunately have to reject this request for now.

**Comment by andersmmg** [comment]
It looks to me like the range is checked by the ComfortsBaseBlock class, could that not be controlled with a config option?

**Comment by TheIllusiveC4** [comment]
That's a separate check. What happens is that Minecraft checks that you're within a certain usage range before allowing you to even interact with the block, _then_ Comforts checks to see if you're close enough to use it. I could disable the second check, but this only extends the range of use about 1-1.5 blocks further before it is outside the range of the Minecraft check entirely.

**Comment by andersmmg** [comment]
Hmm, I wonder how normal beds work then. I sleep in the vanilla beds on ships and it works perfectly fine, even sets the spawn

**Comment by TheIllusiveC4** [comment]
There's a few possible explanations, one of them being that potentially there's some logic coded into ships that make vanilla beds work but not modded beds like Comforts. Or maybe there's some oversight in my logic that I can't see right now. Ultimately, I wouldn't be able to tell unless I knew more about how Eureka/VS2 is coded, since I'm not sure why it's registering as too far when it shouldn't be, so it might be worth bringing this issue up with those developers to see what they say about it.
