### ISSUE TITLE
[Bug]: Sleeping bag sometimes disappears sometimes after getting up

### ISSUE THREAD

**Issue by emeryplyler** [TheIllusiveC4/Comforts#145]
### Minecraft Version

1.20.1

### What happened?

While playing a custom modpack, whether I click "leave bed" or wait until daybreak, sometimes I don't get the sleeping bag back after using it. I believe placing it using shift-right click and then using it would prevent this but I'm not sure.
I believe it may be caused by incompatibility with the SleepWarp mod, the one that makes time speed up while you're sleeping instead of just making it day/night. It's strange because it only happens occasionally.

### How do you trigger this bug?

1. At night time, find 2 flat blocks and right click while holding sleeping bag
2. Wait

### Loader

Fabric

### Loader Version

Fabric 0.15.9

### API Version

Fabric API 0.92.0

### Mod Version

Comforts 6.3.5

**Comment by TheIllusiveC4** [comment]
Unfortunately, I cannot reproduce this. If this is only in your custom modpack, then please test with _just_ Comforts and SleepWarp and see if this issue occurs. If it doesn't, this may be the result of a conflict with another mod that would need be identified.

As a workaround, I suggest placing the sleeping bag using shift-right-click in order to manually use it which should prevent the sleeping bag from attempting to pick itself back up.

**Comment by emeryplyler** [comment]
I can no longer reproduce the bug. Unsure what caused it, maybe it was because my computer was running a lot of things at once?
