### ISSUE TITLE
[Feature]: Correct russian translation

### ISSUE THREAD

**Issue by alvlasov** [TheIllusiveC4/Comforts#160]
### What is the new feature or improvement?

Hi!

I made a russian translation of the mod. It's manually translated, not by an online translator. Could you add it to repository?
[comforts-fabric-9.0.2+1.21.1-Russian.zip](https://github.com/user-attachments/files/17304232/comforts-fabric-9.0.2%2B1.21.1-Russian.zip)

**Comment by TheIllusiveC4** [comment]
Thank you! Before I add your contribution, I'd like some clarification. Since there is already a Russian translation for the mod that was contributed previously, are you claiming that your translation is correcting some entries or is it just adding the missing ones that are untranslated? Or was your translation made without referencing the existing translation at all?

**Comment by alvlasov** [comment]
Hi! This translation was made without referencing the existing translation at all. The current one lacks some lines, has a lot of mistakes and probably was made using some automatic translator.

**Comment by TheIllusiveC4** [comment]
Okay, understood. Thank you for clarifying.
