### ISSUE TITLE
Hammock not working

### ISSUE THREAD

**Issue by Dragnier** [TheIllusiveC4/Comforts#18]
Video showing what happens: https://youtu.be/oEd88bHD7F8

If you need it, I can also attach an export of the modpack I am working on where I discovered this issue.

Also, here are the configs:

    B:"Auto Pick-Up Sleeping Bag"=true
    B:"Auto Use Sleeping Bags"=true
    B:"Leisure Hammocks"=false
    S:"Sleeping Bag Debuffs" <>
    S:"Sleepy Factor"=3.0
    B:Well-Rested=true
    B:"Insulated Sleeping Bags"=false

**Comment by TheIllusiveC4** [comment]
Which version of Comforts and Forge are you using?

**Comment by Dragnier** [comment]
Comforts 1.12.2-1.2.0
Forge 14.23.4.2757

**Comment by TheIllusiveC4** [comment]
Okay, that's what I was thinking it was. So the latest Forge has an update (ironically, PRed by myself) that breaks the hammock coding. It's going to take a while to get a working update for this issue, but until then please use Forge versions 14.23.4.2754 and below only when using Comforts.

**Comment by Darkmega18** [comment]
Are hammocks meant to reset it to day? or are they meant to set it to nearly night? since I figured being able to sleep off the day to the night would be there use if used for bed, but they're setting it to like next day instead. thats a long nap. :V if "nap" I would think it'd be like a "/time add 4000" or something at the very least, with a cooldown/day restriction perhaps?

**Comment by TheIllusiveC4** [comment]
Hammocks will make you sleep until the evening, when the sun is just about to set. They cannot be used at night. They are pretty much meant to function as the inverse of beds.

**Comment by Darkmega18** [comment]
weeeeell, I got an issue then. cause it's setting it to the start of the day. :V

**Comment by TheIllusiveC4** [comment]
@Darkmega18 
Please make a new issue to report this, as your issue is different than this one. This issue is about the hammock not working at all, in the manner shown in the video linked in the first post. Your issue is that the hammocks are setting the time incorrectly. 

I'll still look into this for you, but I will not be posting any updates or queries about your issue until you report it properly in its own thread.
