### ISSUE TITLE
Exploding Bed Dimension Whitelist/Blacklist Option

### ISSUE THREAD

**Issue by jaxmacky** [TheIllusiveC4/Comforts#24]
comforts-1.12.2-1.4.1.1.jar
MC 1.12.2

Suggestion to add a config option to whitelist/blacklist Dimensions.

Sleeping bag blows up when in another dimension other than Overworld. 

I am using a mod that adds planet type dimensions, and would like the sleeping bag to NOT blow up when used on them. Normal Beds do not blow up in the same dimensions.

**Comment by TheIllusiveC4** [comment]
This shouldn't be necessary, because the explosions only occur if the dimension tells it to. Like so:
https://github.com/TheIllusiveC4/Comforts/blob/49cc7a8eaeaa3f713e688b13f598536d0ff52cfc/src/main/java/c4/comforts/common/blocks/BlockBase.java#L95-L96

Can you tell me what mod you're using for planet type dimensions? I'd have to look into it to see what might be happening to cause this issue.

**Comment by jaxmacky** [comment]
Advanced Rocketry is the Mod I am using for the Planets. 
-AdvancedRocketry-1.12.2-1.5.0-138-universal.jar
-LibVulpes-1.12.2-0.4.0-54-universal.jar

After seeing that very code in the Git, I tested with regular beds too to see, and they did not explode.

**Comment by TheIllusiveC4** [comment]
Okay, I figured out the issue. Advanced Rocketry actually overrides regular beds with their own "space-friendly" copy when you place them down, and these do not have any explosion logic at all which is why they don't explode. Vanilla beds _will_ explode, it's just that Advanced Rocketry never lets you place a real vanilla bed down. Advanced Rocketry needs to override the `WorldProvider#canSleepAt` method so that modded beds like mine do not explode.

**Comment by jaxmacky** [comment]
Thanks, will try and pass that along.
