### ISSUE TITLE
Using Tripwire hooks on hammocks

### ISSUE THREAD

**Issue by Dradon7** [TheIllusiveC4/Comforts#54]
**Pitch:**
Instead of having a separate item to use for hammocks (rope+nail), the mod just used vanilla tripwire hooks.

**Reasons why:**
The rope+nail just feels unnecessary when there's a vanilla item that's already so close in design.

**Comment by TheIllusiveC4** [comment]
I disagree that it's close in design. The tripwire hook has a single balance point, while the rope and nail has two. The tripwire hook has a thinner string, while the rope and nail has thicker rope. These are simple but vital to the look and feel of the hammock.

It's also conceptually confusing. Why would you use a tripwire hook to build a hammock when it's meant for entity detection in redstone builds? How does a tripwire hook fit in with the concept of a hammock? It would also confuse people who have been using this mod for a long time to suddenly change the building method without proper justification.

In addition, the rope and nail has extremely different logic from the vanilla tripwire hooks in the code. I'd have to change and add quite a bit, possibly even be forced to make a whole different item that just looks like the tripwire hooks, which would defeat the purpose of using a vanilla item in the first place. It's not really practical.

I'm quite on-board with the idea of re-using a vanilla item instead of making my own like the rope and nail, but the tripwire hook isn't a suitable replacement and, as far as I'm aware, vanilla does not have a suitable replacement in general.
