### ISSUE TITLE
Sleeping Bag Debuffs don't work

### ISSUE THREAD

**Issue by Scamper10** [TheIllusiveC4/Comforts#55]
#### Versions:
* Comforts: 0.0.2
* Fabric: 0.11.2 (I think)
#### Steps to Reproduce:
1. Acquire a sleeping bag
2. Wait till night or use commands to set the time to night
3. Use the sleeping bag

I have attatched two versions of the config, neither of them work (the extention on the computer is json5, they are txt purely for Github).
[comforts - Copy.txt](https://github.com/TheIllusiveC4/Comforts/files/6369182/comforts.-.Copy.txt)
[comforts.txt](https://github.com/TheIllusiveC4/Comforts/files/6369183/comforts.txt)

**Comment by Scamper10** [comment]
Read the wiki, tried the EXACT format and STILL nothing works.

**Comment by TheIllusiveC4** [comment]
Please follow the bug report template.

Since you mentioned Mod Menu, I assume you're on Fabric? Note the wiki is for Forge, the Fabric format is the one in the configuration comments. Please share your configuration setting so I can check it for errors.

**Comment by TheIllusiveC4** [comment]
Sorry, I see that you've edited your post to include the configs a while ago but I don't get notifications for that and I was unaware. Looking at them, I see that you've used spaces instead of semicolons. Please follow the example in the config comments, like this:
```
"sleepingBagDebuffs"= [
		"minecraft:mining_fatigue;5;15",
		"minecraft:slowness;30;1",
		"minecraft:weakness;60;0"
	]
```
I can confirm that these settings work when I tested them.
