### ISSUE TITLE
Taking any item immediately unlocks all Comfort recipes

### ISSUE THREAD

**Issue by Ayutac** [TheIllusiveC4/Comforts#61]
If you are low on time I volunteer to add proper recipe advancements :)

**Comment by TheIllusiveC4** [comment]
I am unable to reproduce this issue. Giving myself any color wool only unlocks the recipes of that wool type, with the others remaining locked. In addition, the Rope and Nail recipe doesn't unlock until the player has received an iron ingot.

**Comment by Goten87** [comment]
i also start with all Sleeping bags unlocked without any items at all all i have given my self is a crafting bench
on: comforts-forge-1.18-5.0.0.1

**Comment by TheIllusiveC4** [comment]
Did you have any other mods installed when that happened? There are mods/modpacks that unlock all the recipes at the start.

**Comment by JonnyOnSeSocks** [comment]
I had the same issue in the newest version without any other mods installed. I looked into it and found that the tags in the advancements json files for "minecraft:inventory_changed" use "item" instead of "items". Updating the advancement json files in data\comforts\advancements\ to "items" did fix this issue for me.
![grafik](https://user-images.githubusercontent.com/90340834/155881997-f1dd153c-6995-4985-9803-0e7081cc1a85.png)

**Comment by Ayutac** [comment]
That should be it. I remember having the same bug in my own mod.
