### ISSUE TITLE
Crash while loading with 1.12.1 using version 1.12.2-1.1.0

### ISSUE THREAD

**Issue by Darkmega18** [TheIllusiveC4/Comforts#8]
[crash-2017-12-01_19.32.18-client.txt](https://github.com/TheIllusiveC4/Comforts/files/1520887/crash-2017-12-01_19.32.18-client.txt)

I'm using it still on 1.12.1 cause some things in my pack don't have 1.12.2 updated mods. I updated this just today from a really old version, like 0.0.6 or something and my game blows up on load. I'll go back and try 1.0.0.2 to see if it has the same issue. Something about entityentrybuilder.

**Comment by TheIllusiveC4** [comment]
So, it looks like Forge only introduced the EntityEntryBuilder in version 1.12.2-14.23.0.2487. Any version before that will crash, unfortunately. I was unaware of this, but I've now made it so that version 1.1.0 only lists compatibility with 1.12.2 to avoid this problem in the future. Previous versions of Comforts should load fine.

**Comment by Darkmega18** [comment]
Ah, balls. alrighty. latest version available it is then.
