### ISSUE TITLE
Single Ingot Rope Recipe

### ISSUE THREAD

**Issue by pawbap** [TheIllusiveC4/Comforts#83]
#### Versions:
* Minecraft: 1.18.2
* Comforts: 6.2.57
* Fabric Loader: 0.13.3
* Fabric API: 0.50.0
* REI: 8.1.449
#### Observed Behavior: 
There's a second crafting recipe for Rope and Nail when looking at it through the Roughly Enough Items mod, requiring only one iron ingot. When placed into the crafting table, it doesn't actually allow crafting the Rope and Nail...of course.
#### Expected Behavior:
There to be only one recipe. 
#### Steps to Reproduce:
1. Open inventory
2. Search for "Rope and Nail"
3. Click (or press R on) the "Rope and Nail" item
#### Images:
![java_2022-04-15_11-55-21](https://user-images.githubusercontent.com/102625726/163557364-476bab6b-e637-4d05-b914-436d69bbd6c6.png)
![java_2022-04-15_11-55-29](https://user-images.githubusercontent.com/102625726/163557373-627f4859-5dd3-4cec-a15a-cc855b15f523.png)

**Comment by TheIllusiveC4** [comment]
There are actually two recipes. However, the second one isn't correctly listed in Roughly Enough Items so I think this is an REI issue at its core. The second recipe uses an iron ingot and the `c:rope` tag. The problem is probably the fact that, by default, the `c:rope` tag is empty and REI seems to show the input as nothing. Contrast this with JEI on Forge which places a red mark in the spot and details that the blank spot is due to an empty tag ingredient.
